### ISSUE TITLE
Wrong results?

### ISSUE THREAD

**Issue by stdex** [myaghobi/php-frameworks-bench#2]
On my configuration:

```
Intel(R) Core(TM) i5-4670 CPU @ 3.40GHz
Ubuntu 20.04.3 LTS, php 8.1
```

```
|framework          |requests per second|relative|peak memory|relative|
|-------------------|------------------:|-------:|----------:|-------:|
|fatfree-3.7.3      |           9,224.12| 9,224.1|       0.39|     0.4|

|framework          |requests per second|relative|peak memory|relative|
|-------------------|------------------:|-------:|----------:|-------:|
|slim-4.9           |           6,940.34| 6,940.3|       0.38|     0.4|
```
~35% diff

In your results table ~300% diff

**Comment by myaghobi** [comment]
There is a big difference between these two. 
I'm going to check benchmarks in Linux instead of WSL. 
Please let me know which webserver/config did you use.

**Comment by myaghobi** [comment]
> On my configuration:
> 
> ```
> Intel(R) Core(TM) i5-4670 CPU @ 3.40GHz
> Ubuntu 20.04.3 LTS, php 8.1
> ```
> 
> ```
> |framework          |requests per second|relative|peak memory|relative|
> |-------------------|------------------:|-------:|----------:|-------:|
> |fatfree-3.7.3      |           9,224.12| 9,224.1|       0.39|     0.4|
> 
> |framework          |requests per second|relative|peak memory|relative|
> |-------------------|------------------:|-------:|----------:|-------:|
> |slim-4.9           |           6,940.34| 6,940.3|       0.38|     0.4|
> ```
> 
> ~35% diff
> 
> In your results table ~300% diff

I got different numbers with Ubuntu(instead of WSL) but the ratio is still the same:

Ubuntu 20.04.3 LTS
LAMP - PHP 8.1
```
|framework          |requests per second|relative|peak memory|relative|
|-------------------|------------------:|-------:|----------:|-------:|
|fatfree-3.7.3      |          15,181.18|15,181.2|       0.40|     0.4|
|slim-4.9           |           4,814.24| 4,814.2|       0.55|     0.6|
```

**Comment by myaghobi** [comment]
I'm closing this issue cause there is no answer after 5 days.
